/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICampaignList, ICampaignListInterface } from "../ICampaignList";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_campaignAddress",
        type: "address",
      },
    ],
    name: "createNewCampaign",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    name: "hasExistingCampaign",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICampaignList__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignListInterface {
    return new utils.Interface(_abi) as ICampaignListInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICampaignList {
    return new Contract(address, _abi, signerOrProvider) as ICampaignList;
  }
}
