/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DexLockerInterface extends ethers.utils.Interface {
  functions: {
    "addLiquidity()": FunctionFragment;
    "coinLockerAddress()": FunctionFragment;
    "getLiquidityReleaseTime()": FunctionFragment;
    "getOwner()": FunctionFragment;
    "liquidityLockerAddress()": FunctionFragment;
    "release()": FunctionFragment;
    "releaseETH()": FunctionFragment;
    "releaseLPTokens()": FunctionFragment;
    "setupLock(uint256,uint256,tuple[8],tuple[8])": FunctionFragment;
    "tokenLockerAddress()": FunctionFragment;
    "totalTokensExpectedToBeLocked()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coinLockerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityReleaseTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidityLockerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseLPTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setupLock",
    values: [
      BigNumberish,
      BigNumberish,
      [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenLockerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokensExpectedToBeLocked",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coinLockerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityReleaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidityLockerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "releaseETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseLPTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setupLock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenLockerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTokensExpectedToBeLocked",
    data: BytesLike
  ): Result;

  events: {};
}

export class DexLocker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DexLockerInterface;

  functions: {
    addLiquidity(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    coinLockerAddress(overrides?: CallOverrides): Promise<[string]>;

    getLiquidityReleaseTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getOwner(overrides?: CallOverrides): Promise<[string]>;

    liquidityLockerAddress(overrides?: CallOverrides): Promise<[string]>;

    release(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    releaseETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    releaseLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setupLock(
      lpReleaseTime: BigNumberish,
      dexListPrice: BigNumberish,
      teamTokenVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      raisedFundVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenLockerAddress(overrides?: CallOverrides): Promise<[string]>;

    totalTokensExpectedToBeLocked(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  addLiquidity(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  coinLockerAddress(overrides?: CallOverrides): Promise<string>;

  getLiquidityReleaseTime(overrides?: CallOverrides): Promise<BigNumber>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  liquidityLockerAddress(overrides?: CallOverrides): Promise<string>;

  release(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  releaseETH(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  releaseLPTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setupLock(
    lpReleaseTime: BigNumberish,
    dexListPrice: BigNumberish,
    teamTokenVestingDetails: [
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      }
    ],
    raisedFundVestingDetails: [
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      },
      {
        releaseDate: BigNumberish;
        releaseAmount: BigNumberish;
        hasBeenClaimed: boolean;
      }
    ],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenLockerAddress(overrides?: CallOverrides): Promise<string>;

  totalTokensExpectedToBeLocked(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addLiquidity(overrides?: CallOverrides): Promise<void>;

    coinLockerAddress(overrides?: CallOverrides): Promise<string>;

    getLiquidityReleaseTime(overrides?: CallOverrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    liquidityLockerAddress(overrides?: CallOverrides): Promise<string>;

    release(overrides?: CallOverrides): Promise<void>;

    releaseETH(overrides?: CallOverrides): Promise<void>;

    releaseLPTokens(overrides?: CallOverrides): Promise<void>;

    setupLock(
      lpReleaseTime: BigNumberish,
      dexListPrice: BigNumberish,
      teamTokenVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      raisedFundVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      overrides?: CallOverrides
    ): Promise<void>;

    tokenLockerAddress(overrides?: CallOverrides): Promise<string>;

    totalTokensExpectedToBeLocked(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addLiquidity(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    coinLockerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityReleaseTime(overrides?: CallOverrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    liquidityLockerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    release(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    releaseETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    releaseLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setupLock(
      lpReleaseTime: BigNumberish,
      dexListPrice: BigNumberish,
      teamTokenVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      raisedFundVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenLockerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    totalTokensExpectedToBeLocked(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    coinLockerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLiquidityReleaseTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidityLockerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    release(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    releaseETH(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    releaseLPTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setupLock(
      lpReleaseTime: BigNumberish,
      dexListPrice: BigNumberish,
      teamTokenVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      raisedFundVestingDetails: [
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        },
        {
          releaseDate: BigNumberish;
          releaseAmount: BigNumberish;
          hasBeenClaimed: boolean;
        }
      ],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenLockerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalTokensExpectedToBeLocked(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
